#!/usr/bin/env node
console.log('=== Kimi Code Setup ===');
console.log('This setup runs during Render build to configure everything.');

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const HOME = process.env.HOME || '/root';
const KIMI_DIR = path.join(HOME, '.kimi-code');
const LOG_DIR = path.join(KIMI_DIR, 'logs');

// Create dirs
[KIMI_DIR, LOG_DIR].forEach(d => {
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
});

// Load existing API keys from current config.toml so redeploys preserve working keys
function loadExistingKeys() {
  const existingPath = path.join(KIMI_DIR, 'config.toml');
  const keys = {};
  try {
    const content = fs.readFileSync(existingPath, 'utf8');
    const lines = content.split('\n');
    let currentProvider = null;
    for (const line of lines) {
      const provMatch = line.match(/^\[providers\.(.+?)\]$/);
      if (provMatch) currentProvider = provMatch[1].replace(/"/g, '');
      const keyMatch = line.match(/^apiKey\s*=\s*"(.+)"$/);
      if (keyMatch && currentProvider) keys[currentProvider] = keyMatch[1];
    }
    console.log(`[setup] Found ${Object.keys(keys).length} existing provider keys in config.toml`);
  } catch(e) { /* no existing config */ }
  return keys;
}
const existingKeys = loadExistingKeys();

// Helper: get key from env var, then existing config (skip placeholders), then fallback
// Checks primary env var first, then optional alt env vars
function getKey(envVar, provider, fallback, ...altEnvVars) {
  if (process.env[envVar]) return process.env[envVar];
  for (const alt of altEnvVars) {
    if (process.env[alt]) return process.env[alt];
  }
  // Skip placeholder/no-auth keys from existing config — they cause 401
  const existing = existingKeys[provider];
  if (existing && existing !== 'no-auth' && existing !== 'no-auth-required' && !existing.startsWith('YOUR_') && !existing.startsWith('sk-YOUR_')) return existing;
  return fallback;
}

// Generate config.toml
const configPath = path.join(KIMI_DIR, 'config.toml');
const defaultModel = process.env.KIMI_DEFAULT_MODEL || 'opencode-deepseek-v4';

const config = `# Kimi Code Configuration - Auto-generated by setup.js
# ALL providers + models from local config

default_model = "${defaultModel}"

[env]
UV_USE_IO_URING = "0"
LIBUV_NO_IO_URING = "1"

server_password = "VNE1wpc7gqGD1THY-Np6WRPYdU5LlOrk3ICvxsy_N58"

# ─── OPENCODE ZEN (primary) ─────────────────────────────────

[providers.opencode]
type = "openai"
apiKey = "${getKey('OPENCODE_API_KEY', 'opencode', 'sk-4yUcUjpt9DuWw7WbHzXtHkMzdLW6QxQPoBZ6mvmI89ljuCSMe0Ac9UtVekDMynfz')}"
base_url = "https://opencode.ai/zen/v1"

[providers.opencode.env]
OPENAI_API_KEY = "no-auth"

# ─── BLUESMINDS ──────────────────────────────────────────────

[providers.bluesminds]
type = "openai"
apiKey = "${getKey('BLUESMINDS_API_KEY', 'bluesminds', 'sk-YOUR_BLUESMINDS_KEY')}"
base_url = "https://api.bluesminds.com/v1"

[providers."bluesminds-backup"]
type = "openai"
apiKey = "${getKey('BLUESMINDS_BACKUP_API_KEY', 'bluesminds-backup', 'sk-YOUR_BLUESMINDS_BACKUP_KEY')}"
base_url = "https://api.bluesminds.com/v1"

# ─── OMNIROUTE (local proxy, 59 models) ──────────────────────

[providers.omniroute]
type = "openai"
apiKey = "no-auth-required"
base_url = "http://127.0.0.1:20128/v1"

# ─── Z-AI (GLM / Zhipu) ──────────────────────────────────────

[providers."z-ai"]
type = "openai"
apiKey = "${getKey('ZAI_API_KEY', 'z-ai', 'YOUR_ZHIPU_KEY')}"
base_url = "https://open.bigmodel.cn/api/paas/v4/"

# ─── ZENMUX ─────────────────────────────────────────────────

[providers.zenmux]
type = "openai"
apiKey = "${getKey('ZENMUX_API_KEY', 'zenmux', 'sk-mg-v1-YOUR_ZENMUX_KEY')}"
base_url = "https://zenmux.ai/api/v1"

# ─── CLOUDFLARE (free, Workers AI via OpenAI-compat endpoint) ─────

[providers.cloudflare]
type = "openai"
apiKey = "${getKey('CLOUDFLARE_API_KEY', 'cloudflare', 'YOUR_CLOUDFLARE_API_KEY')}"
base_url = "https://api.cloudflare.com/client/v4/accounts/5f649ab31f3eea8092b74d83a9706895/ai/v1"

# ═══════════════════════════════════════════════════════════════
# MODELS
# ═══════════════════════════════════════════════════════════════

# ── OmniRoute auto models ──────────

[models."omniroute-auto-best-coding"]
provider = "omniroute"
model = "auto/best-coding"
max_context_size = 1048576

[models."omniroute-auto-best-reasoning"]
provider = "omniroute"
model = "auto/best-reasoning"
max_context_size = 1048576

[models."omniroute-auto-best-fast"]
provider = "omniroute"
model = "auto/best-fast"
max_context_size = 1048576

[models."omniroute-auto-best-vision"]
provider = "omniroute"
model = "auto/best-vision"
max_context_size = 1048576

[models."omniroute-auto-best-chat"]
provider = "omniroute"
model = "auto/best-chat"
max_context_size = 1048576

[models."omniroute-auto-best-coding-fast"]
provider = "omniroute"
model = "auto/best-coding-fast"
max_context_size = 1048576

[models."omniroute-auto-pro-coding"]
provider = "omniroute"
model = "auto/pro-coding"
max_context_size = 1048576

[models."omniroute-auto-pro-reasoning"]
provider = "omniroute"
model = "auto/pro-reasoning"
max_context_size = 1048576

[models."omniroute-auto-pro-vision"]
provider = "omniroute"
model = "auto/pro-vision"
max_context_size = 1048576

[models."omniroute-auto-pro-chat"]
provider = "omniroute"
model = "auto/pro-chat"
max_context_size = 1048576

[models."omniroute-auto-pro-fast"]
provider = "omniroute"
model = "auto/pro-fast"
max_context_size = 1048576

[models."omniroute-auto-coding"]
provider = "omniroute"
model = "auto/coding"
max_context_size = 1048576

[models."omniroute-auto-fast"]
provider = "omniroute"
model = "auto/fast"
max_context_size = 1048576

[models."omniroute-auto-chat"]
provider = "omniroute"
model = "auto/chat"
max_context_size = 1048576

[models."omniroute-auto-cheap"]
provider = "omniroute"
model = "auto/cheap"
max_context_size = 1048576

[models."omniroute-auto-offline"]
provider = "omniroute"
model = "auto/offline"
max_context_size = 1048576

[models."omniroute-auto-smart"]
provider = "omniroute"
model = "auto/smart"
max_context_size = 1048576

[models."omniroute-auto-claude-opus"]
provider = "omniroute"
model = "auto/claude-opus"
max_context_size = 1048576

[models."omniroute-auto-claude-sonnet"]
provider = "omniroute"
model = "auto/claude-sonnet"
max_context_size = 1048576

[models."omniroute-auto-best-free"]
provider = "omniroute"
model = "auto/best-free"
max_context_size = 1048576

[models."omniroute-auto-coding-fast"]
provider = "omniroute"
model = "auto/coding:fast"
max_context_size = 1048576

[models."omniroute-auto-coding-cheap"]
provider = "omniroute"
model = "auto/coding:cheap"
max_context_size = 1048576

[models."omniroute-auto-coding-free"]
provider = "omniroute"
model = "auto/coding:free"
max_context_size = 1048576

[models."omniroute-auto-coding-pro"]
provider = "omniroute"
model = "auto/coding:pro"
max_context_size = 128000

[models."omniroute-auto-coding-reliable"]
provider = "omniroute"
model = "auto/coding:reliable"
max_context_size = 1048576

[models."omniroute-auto-reasoning"]
provider = "omniroute"
model = "auto/reasoning"
max_context_size = 1048576

[models."omniroute-auto-reasoning-pro"]
provider = "omniroute"
model = "auto/reasoning:pro"
max_context_size = 128000

[models."omniroute-auto-vision"]
provider = "omniroute"
model = "auto/vision"
max_context_size = 1048576

[models."omniroute-auto-multimodal"]
provider = "omniroute"
model = "auto/multimodal"
max_context_size = 1048576

[models."omniroute-ddgw-gpt-4o-mini"]
provider = "omniroute"
model = "ddgw/gpt-4o-mini"
max_context_size = 128000

[models."omniroute-ddgw-gpt-5-mini"]
provider = "omniroute"
model = "ddgw/gpt-5-mini"
max_context_size = 400000

[models."omniroute-ddgw-claude-3-5-haiku"]
provider = "omniroute"
model = "ddgw/claude-3-5-haiku-20241022"
max_context_size = 200000

[models."omniroute-ddgw-llama-4-scout"]
provider = "omniroute"
model = "ddgw/llama-4-scout"
max_context_size = 128000

[models."omniroute-ddgw-mistral-small"]
provider = "omniroute"
model = "ddgw/mistral-small-2501"
max_context_size = 128000

[models."omniroute-ddgw-o3-mini"]
provider = "omniroute"
model = "ddgw/o3-mini"
max_context_size = 400000

[models."omniroute-oc-big-pickle"]
provider = "omniroute"
model = "oc/big-pickle"
max_context_size = 200000

[models."omniroute-oc-deepseek-v4-free"]
provider = "omniroute"
model = "oc/deepseek-v4-flash-free"
max_context_size = 1000000

[models."omniroute-oc-minimax-m3-free"]
provider = "omniroute"
model = "oc/minimax-m3-free"
max_context_size = 1048576

[models."omniroute-oc-minimax-m2.5-free"]
provider = "omniroute"
model = "oc/minimax-m2.5-free"
max_context_size = 204800

[models."omniroute-oc-ling-2.6-free"]
provider = "omniroute"
model = "oc/ling-2.6-1t-free"
max_context_size = 200000

[models."omniroute-oc-trinity-free"]
provider = "omniroute"
model = "oc/trinity-large-preview-free"
max_context_size = 200000

[models."omniroute-oc-nemotron-free"]
provider = "omniroute"
model = "oc/nemotron-3-super-free"
max_context_size = 1000000

[models."omniroute-oc-qwen36-free"]
provider = "omniroute"
model = "oc/qwen3.6-plus-free"
max_context_size = 200000

[models."omniroute-tllm-gpt54"]
provider = "omniroute"
model = "tllm/GPT_5_4"
max_context_size = 400000

[models."omniroute-tllm-gpt4o"]
provider = "omniroute"
model = "tllm/GPT_4o"
max_context_size = 200000

[models."omniroute-tllm-claude-opus4"]
provider = "omniroute"
model = "tllm/claude_opus_4"
max_context_size = 200000

[models."omniroute-tllm-claude-sonnet4"]
provider = "omniroute"
model = "tllm/claude_sonnet_4"
max_context_size = 200000

[models."omniroute-tllm-claude-haiku35"]
provider = "omniroute"
model = "tllm/claude_haiku_3_5"
max_context_size = 200000

[models."omniroute-tllm-deepseek-v4"]
provider = "omniroute"
model = "tllm/deepseek_v4"
max_context_size = 200000

[models."omniroute-tllm-gemini3-flash"]
provider = "omniroute"
model = "tllm/gemini_3_flash"
max_context_size = 1000000

[models."omniroute-tllm-gemini3-pro"]
provider = "omniroute"
model = "tllm/gemini_3_pro"
max_context_size = 1000000

# ── OpenCode Zen free models ──────────

[models."opencode-deepseek-v4"]
provider = "opencode"
model = "deepseek-v4-flash-free"
max_context_size = 128000

# Model alias so deepseek-v4-flash-free resolves even when set as default_model
[models."deepseek-v4-flash-free"]
provider = "opencode"
model = "deepseek-v4-flash-free"
max_context_size = 128000

# Also resolve via omniroute (no auth needed, works without API keys)
[models."deepseek-v4-flash-free-omniroute"]
provider = "omniroute"
model = "oc/deepseek-v4-flash-free"
max_context_size = 1000000

[models."opencode-deepseek-v4-pro"]
provider = "opencode"
model = "deepseek-v4-pro"
max_context_size = 128000

[models."opencode-nemotron"]
provider = "opencode"
model = "nemotron-3-ultra-free"
max_context_size = 128000

[models."opencode-north-mini"]
provider = "opencode"
model = "north-mini-code-free"
max_context_size = 128000

[models."opencode-big-pickle"]
provider = "opencode"
model = "big-pickle"
max_context_size = 128000

[models."opencode-qwen36"]
provider = "opencode"
model = "qwen3.6-plus-free"
max_context_size = 128000

[models."opencode-gpt55"]
provider = "opencode"
model = "gpt-5.5"
max_context_size = 128000

[models."opencode-gpt54-mini"]
provider = "opencode"
model = "gpt-5.4-mini"
max_context_size = 128000

[models."opencode-gpt54"]
provider = "opencode"
model = "gpt-5.4"
max_context_size = 128000

[models."opencode-claude-sonnet-4"]
provider = "opencode"
model = "claude-sonnet-4"
max_context_size = 128000

[models."opencode-claude-haiku-4-5"]
provider = "opencode"
model = "claude-haiku-4-5"
max_context_size = 128000

[models."opencode-kimi-k26"]
provider = "opencode"
model = "kimi-k2.6"
max_context_size = 128000

[models."opencode-gemini-35-flash"]
provider = "opencode"
model = "gemini-3.5-flash"
max_context_size = 128000

[models."opencode-minimax-m3"]
provider = "opencode"
model = "minimax-m3-free"
max_context_size = 128000

[models."opencode-mimo-v25"]
provider = "opencode"
model = "mimo-v2.5-free"
max_context_size = 128000

[models."opencode-qwen35"]
provider = "opencode"
model = "qwen3.5-plus"
max_context_size = 128000

[models."opencode-gpt54-nano"]
provider = "opencode"
model = "gpt-5.4-nano"
max_context_size = 128000

[models."opencode-grok"]
provider = "opencode"
model = "grok-build-0.1"
max_context_size = 128000

[models."opencode-glm5"]
provider = "opencode"
model = "glm-5.2"
max_context_size = 128000

# ── Bluesminds models ────────────

[models."bluesminds-gpt4o"]
provider = "bluesminds"
model = "gpt-4o"
max_context_size = 128000

[models."bluesminds-gpt4o-mini"]
provider = "bluesminds"
model = "gpt-4o-mini"
max_context_size = 128000

[models."bluesminds-gpt55"]
provider = "bluesminds"
model = "gpt-5.5"
max_context_size = 128000

[models."bluesminds-gpt5-mini"]
provider = "bluesminds"
model = "gpt-5-mini"
max_context_size = 128000

[models."bluesminds-gpt54"]
provider = "bluesminds"
model = "gpt-5.4"
max_context_size = 128000

[models."bluesminds-gpt52-chat"]
provider = "bluesminds"
model = "gpt-5.2-chat"
max_context_size = 128000

[models."bluesminds-gpt5-nano"]
provider = "bluesminds"
model = "gpt-5-nano"
max_context_size = 128000

[models."bluesminds-gpt5-chat"]
provider = "bluesminds"
model = "gpt-5-chat"
max_context_size = 128000

[models."bluesminds-gpt35"]
provider = "bluesminds"
model = "gpt-3.5-turbo-0613"
max_context_size = 128000

[models."bluesminds-minimax-m2"]
provider = "bluesminds"
model = "minimax-m2"
max_context_size = 128000

[models."bluesminds-minimax-m27"]
provider = "bluesminds"
model = "MiniMax-M2.7"
max_context_size = 128000

[models."bluesminds-deepseek-v4-flash"]
provider = "bluesminds"
model = "deepseek-v4-flash"
max_context_size = 128000

[models."bluesminds-kimi-k25"]
provider = "bluesminds"
model = "kimi-k2.5"
max_context_size = 128000

[models."bluesminds-gemini-3-flash"]
provider = "bluesminds"
model = "gemini-3-flash-preview"
max_context_size = 128000

[models."bluesminds-gemini-31-pro"]
provider = "bluesminds"
model = "gemini-3.1-pro-preview"
max_context_size = 128000

[models."bluesminds-glm46"]
provider = "bluesminds"
model = "glm-4.6"
max_context_size = 128000

[models."bluesminds-blackbox"]
provider = "bluesminds"
model = "blackbox"
max_context_size = 128000

# ── Z-AI (GLM) models ──────────

[models."glm-4-flash"]
provider = "z-ai"
model = "glm-4-flash"
max_context_size = 128000

[models."glm-4-flashx"]
provider = "z-ai"
model = "glm-4-flashx"
max_context_size = 128000

[models."glm-4-air"]
provider = "z-ai"
model = "glm-4-air"
max_context_size = 128000

[models."glm-4-plus"]
provider = "z-ai"
model = "glm-4-plus"
max_context_size = 128000

[models."glm-47-flash"]
provider = "z-ai"
model = "glm-4.7-flash-free"
max_context_size = 128000

[models."glm-5"]
provider = "z-ai"
model = "glm-5"
max_context_size = 128000

[models."glm-52"]
provider = "z-ai"
model = "glm-5.2"
max_context_size = 128000

# ── ZenMux models ──────────

[models."zenmux-default"]
provider = "zenmux"
model = "default"
max_context_size = 128000

[models."zenmux-smart"]
provider = "zenmux"
model = "smart"
max_context_size = 128000

[models."zenmux-fast"]
provider = "zenmux"
model = "fast"
max_context_size = 128000

[models."zenmux-cheap"]
provider = "zenmux"
model = "cheap"
max_context_size = 128000

# ── Cloudflare free models ────

[models."cf-llama31-8b"]
provider = "cloudflare"
model = "@cf/meta/llama-3.1-8b-instruct-fp8"
max_context_size = 32000

[models."cf-llama32-3b"]
provider = "cloudflare"
model = "@cf/meta/llama-3.2-3b-instruct-q8"
max_context_size = 16000

[models."cf-qwen-14b"]
provider = "cloudflare"
model = "@cf/qwen/qwen2.5-14b-instruct-awq"
max_context_size = 32000

[models."cf-deepseek-r1"]
provider = "cloudflare"
model = "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"
max_context_size = 16000

[models."cf-hermes-2"]
provider = "cloudflare"
model = "@cf/nousresearch/hermes-2-pro-llama-3-8b"
max_context_size = 32000

[models."cf-mistral-7b"]
provider = "cloudflare"
model = "@cf/mistral/mistral-7b-instruct-v0.3"
max_context_size = 16000
`;

fs.writeFileSync(configPath, config);
console.log('[setup] Config written to', configPath);
console.log('[setup] Config size:', Buffer.byteLength(config, 'utf8'), 'bytes');

// Verify kimi binary
try {
  const whichKimi = execSync('which kimi 2>/dev/null || npx --yes @moonshot-ai/kimi-code --version 2>/dev/null || echo "not-found"', { encoding: 'utf8' }).trim();
  console.log('[setup] Kimi binary:', whichKimi);
} catch (e) {
  console.log('[setup] Kimi not yet installed (will be available after npm install)');
}

console.log('=== Setup Complete ===');
